### PR TITLE
fix: rework translation-unit top-level items to disallow binary expressions 

### LINKED ISSUE #48: Error parsing a declaration
Hi, I think that the following declaration is causing a parsing error : 
```c
TSLanguage *(*lang_parser)(void);
```

The outputed tree is (tested on the playground) : 
```
translation_unit [0, 0] - [1, 0])
  expression_statement [0, 0] - [0, 33])
    binary_expression [0, 0] - [0, 32])
      left: identifier [0, 0] - [0, 10])
      right: call_expression [0, 12] - [0, 32])
        function: parenthesized_expression [0, 12] - [0, 26])
          pointer_expression [0, 13] - [0, 25])
            argument: identifier [0, 14] - [0, 25])
        arguments: argument_list [0, 26] - [0, 32])
          identifier [0, 27] - [0, 31])
```

It seems wrong as this should be a `declaration` node.

### PR DESCRIPTION
**Pull request by amaanq**
Closes #48 

I don't like how this looks with the nearly repeated rule, but it's the best option I could think of that didn't impact state count too much, maybe some JS-magic could make it look prettier with manipulating top_level_item

@XVilka if you have some more test cases I could add them

cc @ahlinc

### CODE REVIEW

**Comment by XVilka** [comment]
@amaanq no additional testcases, sorry, but this one should be sufficient.

**Comment by amaanq** [comment]
That one seems to work on master, but good to add

**Review by ahlinc — APPROVED** [review]

File: grammar.js [hunk 1]
```diff
@@ -67,7 +68,34 @@ module.exports = grammar({
   word: $ => $.identifier,
 
   rules: {
-    translation_unit: $ => repeat($._top_level_item),
+    translation_unit: $ => repeat(choice(
```
Comment (aryx) [inline grammar.js:71]: It's not clear what is the difference with top_level_item.
I'd rather make the difference explicit by introducing intermediate rules like
top_level_item_no_xxx
statement_no_xxx

File: grammar.js [hunk 2]
```diff
@@ -648,6 +676,35 @@ module.exports = grammar({
       $._statement,
     ),
 
+    _top_level_expression_statement: $ => seq(
+      optional(choice(
```
Comment (aryx) [inline grammar.js:680]: same, it's not clear what is the difference with the general expression.

**Review by aryx — CHANGES_REQUESTED** [review]

File: grammar.js (hunk 1 above)
Comment (ahlinc) [reply grammar.js:71]: Like rename `_top_level_item` to `_block_item` and wrap the above to the actual `_top_level_item` and inline both?

Comment (ahlinc) [reply grammar.js:71]: What do you mean by `no_xxx`? How do you want to count something?

Comment (aryx) [reply grammar.js:71]: I mean that the list looks like the inline content of the top_level_item and the statement rule, but obviously it's not, so there must be certain statements that are not in it (it's still not clear to me which statements are not in it), which is why I proposed to rename to statements_no_xxx to be more explicit about the difference.

Comment (amaanq) [reply grammar.js:71]: binary_expression, since that conflicts w/ pointer declarators, I'll rework it and add a comment explaining which one's missing

File: grammar.js (hunk 2 above)
Comment (amaanq) [reply grammar.js:685]: updated

File: grammar.js [hunk 3]
```diff
@@ -44,7 +44,7 @@ module.exports = grammar({
 
   inline: $ => [
     $._statement,
-    $._top_level_item,
```
Comment (ahlinc) [inline grammar.js:47]: I think the `_top_level_item` also should be inlined to reduce an internal tree complexity. Of course if it doesn't produces compilation errors, because I'm not sure by looking only on a changed piece of the grammar :shrug:

File: grammar.js [hunk 4]
```diff
@@ -69,7 +70,37 @@ module.exports = grammar({
   rules: {
     translation_unit: $ => repeat($._top_level_item),
 
+    // Top level items are block items with the exception of the expression statement
     _top_level_item: $ => choice(
```
Comment (aryx) [inline grammar.js:74]: One issue with this is that if one day one add a new kind of statement, then he will need to add it also there, and it's easy to forget. If instead we factorize things with
block_item_no_expr_statement,  and then have block_item: choice(block_item_no_expr_statement, expr_statement),
then we would need to modify only one place.

File: grammar.js [hunk 5]
```diff
@@ -649,6 +680,36 @@ module.exports = grammar({
       $._statement,
     ),
 
+    // This is missing binary expressions, others were kept so that macro code can be parsed better and code examples
+    _top_level_expression_statement: $ => seq(
```
Comment (aryx) [inline grammar.js:684]: same here, we could factorize things by using
a _expression_no_binary_exprs intermediate rule.

File: grammar.js [hunk 6]
```diff
@@ -649,6 +680,36 @@ module.exports = grammar({
       $._statement,
     ),
 
+    // This is missing binary expressions, others were kept so that macro code can be parsed better and code examples
```
Comment (aryx) [inline grammar.js:683]: would be good to say why we skipped binary expressions. what's the problem with binary expression at the top?

Comment (aryx) [reply grammar.js:683]: If it's because of this ambiguity with pointer expressions, could have been solved in another way? by playing with dynamic priorities?

**Review by aryx — APPROVED** [review]

**Review by ahlinc — CHANGES_REQUESTED** [review]

File: grammar.js (hunk 3 above)
Comment (amaanq) [reply grammar.js:47]: oops, done

File: grammar.js (hunk 6 above)
Comment (amaanq) [reply grammar.js:684]: Yeah I did try a lot w/ dynamic precendences, but that caused other issues elsewhere mainly and sometimes didn't do anything as well

**Review by ahlinc — APPROVED** [review]

**Comment by amaanq** [comment]
reworked

**Comment by XVilka** [comment]
@amaanq as you rework top level statement, I wonder if it makes sense to also target this case: https://github.com/tree-sitter/tree-sitter-c/issues/129

**Comment by amaanq** [comment]
I'm not sure about that one, I think it is *correct* to associate the pointer declarator with foo

**Comment by amaanq** [comment]
I reworked it anyways just for top level functions..if that proves to be incorrect/disputed I will revert @XVilka

**Comment by amaanq** [comment]
Actually, that breaks error recovery a bit in upstream tests and still doesn't fit fully right w/ me, so I reverted it, sorry. That needs a better solution than what I had
